---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.name }}-service
  labels:
    app: {{ .Chart.name }}
    version: {{ .Chart.version }}
spec:
  replicas: {{ .values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.name }}-dc
          image: {{ .values.dockerImage }}
          ports:
            - name: http
              containerPort: {{ .values.portInternal }}
          volumeMounts:
            - name: file-volume
              mountPath: /data
      volumes:
        - name: file-volume
          configMap:
            defaultMode: 0700
            name: {{ .Chart.name }}-cm
