---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-service
  labels:
    app: {{ .Chart.Name }}
    version: {{ .Chart.Version }}
spec:
  selector:
    app: {{ .Chart.Name }}
  type: LoadBalancer
  ports:
    - name: http
      protocol: {{ .values.serverProtocol }}
      port: 80
      targetPort: {{ .Values.portInternal }}
      nodePort: {{ .Values.portExternal }}
